### ISSUE TITLE
Incompatibility with Monitor#broadcast & ActiveRecord ConnectionPool

### ISSUE THREAD

**Issue by delonnewman** [digital-fabric/polyphony#113]
When trying to use Polyphony with Ruby 3.0.3 & Rails 7.0.6 I get the following error when I try to drop the database:

`NoMethodError: undefined method 'mon_check_owner' for #<Polyphony::Mutex:0x000000015847d228 @store=#<Polyphony::Queue:0x000000015847d188>, @token=nil, @holding_fiber=nil>`

Please let me know if there's any more I can do to help and thank you for your hard work!

This is the full trace:

```
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:drop
** Invoke db:drop:_unsafe (first_time)
** Invoke db:load_config 
** Execute db:drop:_unsafe
undefined method `mon_check_owner' for #<Polyphony::Mutex:0x000000015847d228 @store=#<Polyphony::Queue:0x000000015847d188>, @token=nil, @holding_fiber=nil>
Couldn't drop database 'dragnet_development'
rails aborted!
NoMethodError: undefined method `mon_check_owner' for #<Polyphony::Mutex:0x000000015847d228 @store=#<Polyphony::Queue:0x000000015847d188>, @token=nil, @holding_fiber=nil>
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/monitor.rb:141:in `broadcast'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:154:in `broadcast_on_biased'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:187:in `block in with_a_bias_for'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/monitor.rb:202:in `mon_synchronize'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:80:in `synchronize'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:185:in `ensure in with_a_bias_for'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:185:in `with_a_bias_for'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:536:in `attempt_to_checkout_all_existing_connections'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:522:in `block in with_exclusively_acquired_all_connections'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:598:in `with_new_connections_blocked'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `with_exclusively_acquired_all_connections'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `disconnect'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:269:in `disconnect!'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/pool_config.rb:47:in `block in disconnect!'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/mutex_m.rb:78:in `synchronize'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/mutex_m.rb:78:in `mu_synchronize'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/pool_config.rb:43:in `disconnect!'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_handler.rb:226:in `remove_connection_pool'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/connection_handler.rb:135:in `establish_connection'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/connection_handling.rb:52:in `establish_connection'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `establish_connection'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/postgresql_database_tasks.rb:97:in `establish_master_connection'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/postgresql_database_tasks.rb:31:in `drop'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:224:in `drop'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:239:in `block in drop_current'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:554:in `each'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:553:in `each'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:239:in `drop_current'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <top (required)>'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.6/lib/active_record/railties/databases.rake:64:in `block (2 levels) in <top (required)>'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/command.rb:51:in `invoke'
/Users/delonnewman/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop:_unsafe

```

**Comment by noteflakes** [comment]
Thanks for reporting this, I'm working on a fiber-aware implementation of the `Monitor` class. This will take a couple of a weeks.
