### ISSUE TITLE
Problems with concurrent-ruby

### ISSUE THREAD

**Issue by primeapple** [digital-fabric/polyphony#50]
Hey there,
I found another issue. So I have a project, that is based on Rails, in particular ActiveSupport. This however depends on concurrent-ruby.
Now it seems to be a problem to have Polyphony work together with concurrent-ruby. My Stacktrace says the following

```
/home/me/.rvm/gems/ruby-2.7.2@test/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:38:in `synchronize': undefined method `owned?' for #<Polyphony::Mutex:0x0000557126478d70> (NoMethodError)
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/atomic/event.rb:42:in `initialize'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/object.rb:59:in `new'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/object.rb:59:in `new'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/immediate_executor.rb:22:in `initialize'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/object.rb:59:in `new'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/object.rb:59:in `new'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/queue_adapters/async_adapter.rb:88:in `initialize'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/queue_adapters/async_adapter.rb:36:in `new'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/queue_adapters/async_adapter.rb:36:in `initialize'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/queue_adapter.rb:37:in `new'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/queue_adapter.rb:37:in `queue_adapter='
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/queue_adapter.rb:14:in `block in <module:QueueAdapter>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/concern.rb:122:in `class_eval'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/concern.rb:122:in `append_features'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/base.rb:63:in `include'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/base.rb:63:in `<class:Base>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/base.rb:61:in `<module:ActiveJob>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/base.rb:15:in `<top (required)>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/test_helper.rb:34:in `<module:TestHelper>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/test_helper.rb:7:in `<module:ActiveJob>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/test_helper.rb:5:in `<top (required)>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activejob-6.0.3.4/lib/active_job/railtie.rb:35:in `block (2 levels) in <class:Railtie>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/actionpack-6.0.3.4/lib/action_dispatch/testing/integration.rb:641:in `block in <module:Behavior>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/concern.rb:122:in `class_eval'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/activesupport-6.0.3.4/lib/active_support/concern.rb:122:in `append_features'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/actionpack-6.0.3.4/lib/action_dispatch/testing/integration.rb:672:in `include'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/actionpack-6.0.3.4/lib/action_dispatch/testing/integration.rb:672:in `<class:IntegrationTest>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/actionpack-6.0.3.4/lib/action_dispatch/testing/integration.rb:622:in `<module:ActionDispatch>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/actionpack-6.0.3.4/lib/action_dispatch/testing/integration.rb:12:in `<top (required)>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/railties-6.0.3.4/lib/rails/test_help.rb:10:in `<top (required)>'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	from /home/me/.rvm/gems/ruby-2.7.2@test/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
       ...
```
It seems that Polyphony overwrites the Mutex Class of Concurrent-ruby. Does that make sense?

**Comment by ciconia** [comment]
Hi primeapple, thanks for reporting this issue and sorry for the late reply. I've just pushed version 0.54.0 which should solve this issue. Please test and let me know (though frankly I very much suspect you'll run into many more issues before being able to run Rails on Polyphony).

**Comment by ciconia** [comment]
Closing for lack of response. Let me know if you're still having problems.
