### ISSUE TITLE
osx, symbol not found in flat namespace '_Backend_close'

### ISSUE THREAD

**Issue by dm1try** [digital-fabric/polyphony#70]
Hi there!
after upgrading from `0.73` to `0.75` I started to receive the error mentioned in the title.

osx 12.1 (21C52), ruby  2.7.3
the minimal reproducible example
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'polyphony', '0.75'
end

puts 'It works!'
```
leads to
```
ruby test_polyphony.rb
Traceback (most recent call last):
	11: from test_polyphony.rb:3:in `<main>'
	10: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/inline.rb:55:in `gemfile'
	9: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/settings.rb:131:in `temporary'
	8: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/inline.rb:71:in `block in gemfile'
	7: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/runtime.rb:50:in `require'
	6: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/runtime.rb:50:in `each'
	5: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/runtime.rb:61:in `block in require'
	4: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/runtime.rb:61:in `each'
	3: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/runtime.rb:66:in `block (2 levels) in require'
	2: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/runtime.rb:66:in `require'
	1: from /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/polyphony-0.75/lib/polyphony.rb:4:in `<top (required)>'
/Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/polyphony-0.75/lib/polyphony.rb:4:in `require_relative': dlopen(/Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/polyphony-0.75/lib/polyphony_ext.bundle, 0x0009): symbol not found in flat namespace '_Backend_close' - /Users/dmitrydedov/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/polyphony-0.75/lib/polyphony_ext.bundle (LoadError)
```

**Comment by ciconia** [comment]
Thanks for reporting this, fixed in version 0.76.
