### ISSUE TITLE
symbol not found in flat namespace '_Backend_tee'

### ISSUE THREAD

**Issue by tonydaly** [digital-fabric/polyphony#85]
Heya,

Just tried to install (on an M1 Pro, MacOS 12.3) and received this error:

```
/Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/polyphony-0.86/lib/polyphony.rb:4:in `require_relative': dlopen(/Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/polyphony-0.86/lib/polyphony_ext.bundle, 0x0009): symbol not found in flat namespace '_Backend_tee' - /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/polyphony-0.86/lib/polyphony_ext.bundle (LoadError)
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/polyphony-0.86/lib/polyphony.rb:4:in `<top (required)>'
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:66:in `require'
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/bundler/inline.rb:71:in `block in gemfile'
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/bundler/settings.rb:131:in `temporary'
	from /Users/tony/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/bundler/inline.rb:55:in `gemfile'
	from test_polyphony.rb:3:in `<main>'
```

I tried the reproducible setup from #70. I was originally on Ruby 3.0.2, so thought i'd try upgrading to 3.1.1, but received teh same error.

Any help appreciated!

**Comment by ciconia** [comment]
Thanks for reporting this. Please try to install Polyphony 0.87 (just released) and let me know if this solves the problem.

**Comment by ciconia** [comment]
I'm closing this issue. Please let me know if you have any more problems.
